Add nonceCondition
brinktrade/brink-sdk pull request #101
Opened 2023-09-21 13:05 UTC by phanpak

2023-09-21 13:06 UTC, phanpak commented on test/local/DSL/nonceCondition.test.ts
> +    edgeCases.forEach(testCase => {
This style of testing is very popular in Go. I don't know if you guys are ok with it. I can split into their own tests if you prefer.

2023-09-21 13:08 UTC, phanpak commented on test/local/DSL/nonceCondition.test.ts
> +    edgeCases.forEach(testCase => {
and also a lot of these tests feel like testing nonceToBit which i'm not sure is useful. wdyt?

2023-09-21 13:20 UTC, phanpak commented on src/strategies/DSL/conditions/nonceCondition.ts
> +            bit: bit.value,
@mikec do you mind checking what values we need for other parameters? 

* chainId
* signer

chainId is optional and signer is mandatory.

2023-09-22 00:17 UTC, mikec requested changes

2023-09-22 00:17 UTC, mikec commented on src/strategies/DSL/conditions/nonceCondition.ts
> +          functionName: 'requireBitUsed',
I hadn't actually added primitive classes for the `requireBitUsed` and `requireBitNotUsed` functions yet, so I just did that and merged them to v5. You should rebase v5 branch so these are supported.

params expected are index and value. See how it's set up in tests here https://github.com/brinktrade/brink-sdk/blob/41c34a0b1bae8d5ad08314a7437de78fdda2af8b/test/local/Strategies.test.ts#L330

2023-09-22 16:16 UTC, phanpak commented on src/strategies/DSL/conditions/nonceCondition.ts
> +const STATE_USED = 'USED'
done

2023-09-25 09:24 UTC, phanpak commented on test/local/DSL/nonceCondition.test.ts
> +    edgeCases.forEach(testCase => {
done

2023-09-25 15:01 UTC, mikec commented on test/local/nonceToBit.test.ts
> +  const edgeCases = [
awesome, thanks for adding the additional test cases!

2023-09-25 15:01 UTC, mikec approved these changes

2023-09-25 22:52 UTC, mikec approved these changes

2023-09-26 00:58 UTC, merged